# Generated by Django 4.1.7 on 2023-03-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registor_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=500)),
                ('Phone_no', models.IntegerField(unique=True)),
                ('Email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registor_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_no', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('spam', models.BooleanField(default=False)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spam_check.registor_user')),
            ],
        ),
    ]
