# Generated by Django 4.1.7 on 2023-03-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spam_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registor_contact',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spam_check.registor_user'),
        ),
    ]
