# Generated by Django 4.1.7 on 2023-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_check', '0002_alter_registor_contact_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registor_contact',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
